### ISSUE TITLE
error when using lpanda command CLI

### ISSUE THREAD

**Issue by reopucino** [pixelpicosean/lesser-panda#32]
i have try create first new project but when using lpanda create MyAwesomeGame. i got an error like this

```
Mac-mini:htdocs reopucino$ lpanda create myawesome
/usr/local/lib/node_modules/lesser-panda-cli/utils.js:9
  for (let i = 0; i < files.length; i++) {
       ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/lesser-panda-cli/build.js:9:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by pixelpicosean** [comment]
Cause your node version is a little bit low that does not support ES2015 natively, any `v6.0+` should work.
Recommend [nvm](https://github.com/creationix/nvm) if you need to manage multiple node installs.

**Comment by reopucino** [comment]
thanks for fast respond.. will check your recommendation first
